#!/usr/bin/env bash
# 01-system.sh — host basics. Deliberately does NOT touch the driver/CUDA stack.
# On DGX OS the GPU stack is a validated LTS bundle updated on NVIDIA's cadence;
# the supported way to get newer CUDA is NGC containers, not host installs.
set -euo pipefail
source "$(dirname "$0")/../lib/common.sh"
require_dgx

step "Host system setup (userspace only — driver/CUDA left untouched)"

# --- data directories -------------------------------------------------------
log "Creating data directories under ${DATA_ROOT}"
mkdir -p "$DATA_ROOT" "$HF_HOME" "$MODELS_DIR" "$OLLAMA_MODELS"
ok "Directories ready"

# --- docker without sudo ----------------------------------------------------
if ! groups "$USER" | grep -qw docker; then
  log "Adding $USER to the docker group"
  sudo_ usermod -aG docker "$USER"
  warn "Log out and back in (or run: newgrp docker) for group change to take effect."
else
  ok "$USER already in docker group"
fi

# --- safe, arch-generic CLI tooling -----------------------------------------
# None of these touch CUDA. nvtop gives you a live GPU view; perftest/ibverbs
# are for validating the QSFP link later; iperf3 for the TCP-side check.
apt_ensure \
  htop nvtop jq git tmux curl wget unzip ncdu tree \
  iperf3 rsync ca-certificates gnupg lsof \
  python3-venv python3-pip pipx \
  rdma-core perftest ibverbs-utils

# --- uv (fast Python env manager; nice for host-side glue scripts) ----------
if ! have uv; then
  log "Installing uv (user-local)"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  ok "uv installed to ~/.local/bin (ensure it's on PATH)"
else
  ok "uv present: $(uv --version)"
fi

# --- persist HF cache + Ollama model location for all shells ----------------
PROFILE_SNIPPET="${HOME}/.config/dgx-spark.env.sh"
mkdir -p "$(dirname "$PROFILE_SNIPPET")"
cat > "$PROFILE_SNIPPET" <<EOF
# Auto-generated by dgx-spark-setup/01-system.sh
export HF_HOME="${HF_HOME}"
export HUGGING_FACE_HUB_TOKEN="${HF_TOKEN}"
export OLLAMA_MODELS="${OLLAMA_MODELS}"
export PATH="\$HOME/.local/bin:\$PATH"
EOF
if ! grep -q 'dgx-spark.env.sh' "${HOME}/.bashrc" 2>/dev/null; then
  echo "[ -f \"$PROFILE_SNIPPET\" ] && source \"$PROFILE_SNIPPET\"" >> "${HOME}/.bashrc"
  ok "Hooked env snippet into ~/.bashrc"
fi
ok "Environment persisted at ${PROFILE_SNIPPET}"

# --- UMA quality-of-life: install the workload helpers ----------------------
install -m 0755 "${REPO_ROOT}/helpers/flush-cache.sh" "${HOME}/.local/bin/spark-flush-cache" 2>/dev/null || true
install -m 0755 "${REPO_ROOT}/helpers/gpu.sh"         "${HOME}/.local/bin/spark-gpu"         2>/dev/null || true
install -m 0755 "${REPO_ROOT}/helpers/health.sh"      "${HOME}/.local/bin/spark-health"      2>/dev/null || true
ok "Installed helpers: spark-gpu, spark-flush-cache, spark-health"

echo
ok "Host setup complete."
warn "If you were just added to the docker group, start a new shell before continuing."
log "Next: dgxsetup security   (hardening + Tailscale)"
