#!/usr/bin/env bash
# 10-cluster-serve.sh — pooled "big" model serving across BOTH Sparks.
#
# This is the glue between your platform and the community multi-node engine
# (mark-ramsey-ri/vllm-dgx-spark). That repo does what your single-node stack
# can't: split ONE large model across both GB10s with tensor parallelism (Ray +
# NCCL over your validated RoCE fabric). This wrapper drives it from HERE, using
# values from your .env, and exposes the result to your LiteLLM gateway as 'big'.
#
# You already staged + validated the fabric with 09-cluster.sh, so that repo's
# entire multi-Spark OS-setup section is skipped — the link is done.
#
# Subcommands:
#   ./setup.sh cluster-serve setup          clone the repo + generate its config + preflight
#   ./setup.sh cluster-serve start          launch the pooled model, health-check the endpoint
#   ./setup.sh cluster-serve status         is the cluster up? which model?
#   ./setup.sh cluster-serve logs           tail the cluster/vLLM logs
#   ./setup.sh cluster-serve stop           tear the cluster down
#   ./setup.sh cluster-serve sync-gateway   re-point LiteLLM's 'big' route at the current BIG_MODEL
#
# MEMORY: a big TP model at ${BIG_GPU_MEM_UTIL} util claims most of both boxes'
# 128 GB. You cannot also hold the single-node fast model on the head at the same
# time — "big" and "fast" are mutually exclusive serving modes on this hardware.
set -euo pipefail
source "$(dirname "$0")/../lib/common.sh"
require_dgx

VENDOR="${CLUSTER_VENDOR_DIR:-${DATA_ROOT}/vendor/vllm-dgx-spark}"
CMD="${1:-help}"

# ---------------------------------------------------------------------------
preflight() {
  local ok=1
  [[ -n "${CLUSTER_WORKER_MGMT}" ]] || { err "CLUSTER_WORKER_MGMT is empty in .env (worker's LAN/Tailscale IP)."; ok=0; }
  [[ -n "${HF_TOKEN}" ]] || warn "HF_TOKEN empty — gated big models (Llama, etc.) won't download."
  # fabric up?
  if ping -c1 -W2 "${CLUSTER_PEER_IP}" >/dev/null 2>&1; then
    ok "Fabric up: peer ${CLUSTER_PEER_IP} reachable (this is the NCCL/RDMA path)."
  else
    err "Peer ${CLUSTER_PEER_IP} not reachable — run './setup.sh cluster stage' on both nodes first."; ok=0
  fi
  # head -> worker passwordless SSH? (the repo SSHes from head to worker)
  if [[ -n "${CLUSTER_WORKER_MGMT}" ]]; then
    if ssh -o BatchMode=yes -o ConnectTimeout=5 "${CLUSTER_WORKER_USER}@${CLUSTER_WORKER_MGMT}" hostname >/dev/null 2>&1; then
      ok "Passwordless SSH head→worker works (${CLUSTER_WORKER_USER}@${CLUSTER_WORKER_MGMT})."
    else
      err "No passwordless SSH to the worker. Fix: ssh-copy-id ${CLUSTER_WORKER_USER}@${CLUSTER_WORKER_MGMT}"; ok=0
    fi
  fi
  [[ $ok -eq 1 ]]
}

gen_config() {
  # Write the vendor repo's config.local.env from OUR .env — single source of truth.
  cat > "${VENDOR}/config.local.env" <<EOF
# Auto-generated by dgx-spark-setup/10-cluster-serve.sh — do not hand-edit.
WORKER_HOST="${CLUSTER_WORKER_MGMT}"
WORKER_IB_IP="${CLUSTER_PEER_IP}"
WORKER_USER="${CLUSTER_WORKER_USER}"
MODEL="${BIG_MODEL}"
TENSOR_PARALLEL="${BIG_TP}"
GPU_MEMORY_UTIL="${BIG_GPU_MEM_UTIL}"
MAX_MODEL_LEN="${BIG_MAX_MODEL_LEN}"
HF_TOKEN="${HF_TOKEN}"
EOF
  ok "Wrote ${VENDOR}/config.local.env (MODEL=${BIG_MODEL}, TP=${BIG_TP})."
}

# ---------------------------------------------------------------------------
setup() {
  step "Set up the pooled-serving engine"
  mkdir -p "$(dirname "$VENDOR")"
  if [[ -d "${VENDOR}/.git" ]]; then
    log "Repo present — pulling latest."
    git -C "$VENDOR" pull --ff-only || warn "git pull failed (local changes?); continuing with what's on disk."
  else
    log "Cloning ${CLUSTER_REPO_URL}"
    git clone --depth 1 "${CLUSTER_REPO_URL}" "$VENDOR"
  fi
  [[ -f "${VENDOR}/start_cluster.sh" ]] || die "start_cluster.sh not found in ${VENDOR} — repo layout changed? Check ${CLUSTER_REPO_URL}."
  chmod +x "${VENDOR}"/*.sh 2>/dev/null || true

  gen_config
  echo
  preflight || warn "Preflight found issues above — resolve them before 'start'."
  echo
  warn "Cache: this repo defaults its model cache to /raid/hf-cache. To reuse your"
  warn "existing downloads at ${HF_HOME}, symlink once (both Sparks):"
  warn "    sudo mkdir -p /raid && sudo ln -sfn ${HF_HOME} /raid/hf-cache"
  warn "Container: it uses the NGC image nvcr.io/nvidia/vllm:* — if the pull 401s,"
  warn "    run 'docker login nvcr.io' with a free NGC API key."
  log "Next: ./setup.sh cluster-serve start"
}

start() {
  step "Launch pooled model: ${BIG_MODEL} (TP=${BIG_TP}) across both Sparks"
  [[ -d "$VENDOR" ]] || die "Not set up yet. Run: ./setup.sh cluster-serve setup"
  gen_config                       # refresh in case .env changed
  preflight || die "Preflight failed — see errors above."

  # Warn about the fast-mode collision on the same host port space.
  if curl -sf "http://127.0.0.1:${BIG_PORT}/health" >/dev/null 2>&1; then
    warn "Something already answers on :${BIG_PORT}. If that's your single-node engine, stop it first (it and the cluster can't share the port)."
  fi

  log "Handing off to the cluster launcher (this pulls images, syncs the model to the worker, starts Ray + vLLM)…"
  ( cd "$VENDOR" && ./start_cluster.sh )

  log "Waiting for the pooled endpoint on 127.0.0.1:${BIG_PORT} (big models load slowly across the link)…"
  for i in $(seq 1 120); do
    if curl -sf "http://127.0.0.1:${BIG_PORT}/health" >/dev/null 2>&1; then
      ok "Pooled endpoint healthy."
      curl -s "http://127.0.0.1:${BIG_PORT}/v1/models" 2>/dev/null | head -c 400 | sed 's/^/    /'; echo
      break
    fi
    sleep 10
    [[ $i -eq 120 ]] && warn "Not healthy yet — big TP loads can take a while. Watch: ./setup.sh cluster-serve logs"
  done

  echo
  ok "Pooled model is (or soon will be) up. It's exposed to your gateway as 'big'."
  cat <<EOF

  Reach it through your existing LiteLLM gateway (no app changes):
    curl http://127.0.0.1:${LITELLM_PORT}/v1/chat/completions \\
      -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \\
      -H "Content-Type: application/json" \\
      -d '{"model":"big","messages":[{"role":"user","content":"hello"}],"max_tokens":32}'

  Your apps: just ask for model "big" instead of "primary".
  If the gateway 404s on 'big', the model name changed — run:
    ./setup.sh cluster-serve sync-gateway
EOF
}

status() {
  step "Pooled cluster status"
  if curl -sf "http://127.0.0.1:${BIG_PORT}/health" >/dev/null 2>&1; then
    ok "Endpoint healthy on :${BIG_PORT}"
    curl -s "http://127.0.0.1:${BIG_PORT}/v1/models" 2>/dev/null | head -c 400 | sed 's/^/    /'; echo
  else
    warn "No healthy endpoint on :${BIG_PORT} (cluster down or still loading)."
  fi
  log "Ray/vLLM containers on this (head) node:"
  docker ps --filter "name=ray-" --format '    {{.Names}}\t{{.Status}}' || true
}

logs() {
  [[ -d "$VENDOR" ]] || die "Not set up yet."
  # Prefer the repo's own diagnostics if present, else tail head container logs.
  if docker ps --format '{{.Names}}' | grep -q '^ray-head$'; then
    docker exec ray-head tail -n 120 -f /var/log/vllm.log 2>/dev/null \
      || docker logs -f ray-head
  else
    warn "ray-head container not running. Start with: ./setup.sh cluster-serve start"
  fi
}

stop() {
  step "Stop the pooled cluster"
  [[ -d "$VENDOR" ]] || die "Not set up yet."
  ( cd "$VENDOR" && ./stop_cluster.sh ) && ok "Cluster stopped (head + workers)."
  log "Port ${BIG_PORT} is free again — you can bring the single-node fast engine back with ./setup.sh inference"
}

sync_gateway() {
  # Re-point LiteLLM's 'big' route at the current BIG_MODEL by re-upping the
  # gateway container so it re-reads BIG_MODEL_LITELLM from .env.
  step "Sync gateway 'big' route to BIG_MODEL=${BIG_MODEL}"
  local C="docker compose -f ${REPO_ROOT}/compose/inference.yml --env-file ${REPO_ROOT}/.env"
  $C --profile "${INFER_ENGINE:-vllm}" up -d litellm
  ok "LiteLLM re-loaded. 'big' now routes to openai/${BIG_MODEL}."
}

case "$CMD" in
  setup)        setup ;;
  start)        start ;;
  status)       status ;;
  logs)         logs ;;
  stop)         stop ;;
  sync-gateway) sync_gateway ;;
  *) grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//' ;;
esac
